//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int TopicId { get; set; }
        public int MaterialId { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    
        public virtual Topic Topic { get; set; }
    }
}
